title: 'S. Hyeon'
path:
  index: 'index.html'
  more: 'more.html'
  readme: 'README.md'
  note_list_yaml: 'list.yaml'
  more: 'more.html'
  categories: 'categories.html'
  languages: 'languages.html'
  stylesheet: 'style.css'
  stylesheet_dark: 'style-dark.css'
  highlight: 'highlight.css'
  sitemap: 'sitemap.xml'
  common_js: 'common.js'
  html_part:
    head: 'head.html'
    tail: 'tail.html'
    recent_notes: 'recent_notes.html'
    list: 'list.html'
    note_list: 'article_list.html'
dir_path:
  md: 'md'
  notes: 'notes'
  html_part: 'html'
  icons: 'icons'
  category: 'category'
  language: 'language'
  katex: 'katex'
ext:
  md: '.md'
  html: '.html'
  css: '.css'
debug:
  math_ph: '{{%%}}'
  math_display_ph: '{{%%%%}}'
  pandoc_cmd:
    - 'pandoc'
    - '-f'
    - 'gfm'
    - '-t'
    - 'html'
license:
  project: 'LICENSE'
  notes: 'LICENSE_NOTE'
  katex: 'LICENSE_KATEX'
github_repo: 'https://github.com/loudcolour/loudcolour.github.io'
site_url: 'https://loudcolour.github.io'
search_url: 'https://cse.google.com/cse?cx=000662269964548083137:nbo_gc_sck0'
recent_notes_amount: 8
